[sqdcollection]
git-tree-sha1 = "d607267220cb3f2cd564dc3231029f229b2e70ae"
lazy = true

    [[sqdcollection.download]]
    sha256 = "5c9bc6a6df327f4d33eeb150df298ed9b1a376bbfc1778114960b4b592b8483d"
    url = "https://github.com/optimizers/sqd-collection/archive/v0.1.tar.gz"
